<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MRVJBNT" failures="0" tests="8" name="com.menumitratCommonAPITestScript.loginTestScript" time="2.572" errors="2" timestamp="27 May 2025 15:59:39 GMT">
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.291"/>
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.631">
    <error message="Negative test case login_006 failed: Error validating response: Error processing success response: Actual response does not match expected response" type="com.menumitra.utilityclass.customException">
      <![CDATA[com.menumitra.utilityclass.customException: Negative test case login_006 failed: Error validating response: Error processing success response: Actual response does not match expected response
	at com.menumitratCommonAPITestScript.loginTestScript.verifyLoginUsingInvalidInputData(loginTestScript.java:327)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyLoginUsingInvalidInputData -->
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.319"/>
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.267"/>
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.311"/>
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyloginUsingValidInputData" time="0.263">
    <error message="Login verification failed: Error validating response: Error processing success response: Actual response does not match expected response" type="com.menumitra.utilityclass.customException">
      <![CDATA[com.menumitra.utilityclass.customException: Login verification failed: Error validating response: Error processing success response: Actual response does not match expected response
	at com.menumitratCommonAPITestScript.loginTestScript.verifyloginUsingValidInputData(loginTestScript.java:256)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyloginUsingValidInputData -->
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.265"/>
  <testcase classname="com.menumitratCommonAPITestScript.loginTestScript" name="verifyLoginUsingInvalidInputData" time="0.225"/>
</testsuite> <!-- com.menumitratCommonAPITestScript.loginTestScript -->
