<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MRVJBNT" failures="0" tests="1" name="com.menumitratCommonAPITestScript.UdhariLeedgerCreateTestScript" time="0.018" errors="1" timestamp="27 May 2025 18:15:53 GMT">
  <testcase classname="com.menumitratCommonAPITestScript.UdhariLeedgerCreateTestScript" name="testUdhariLedgerCreate" time="0.018">
    <error message="Test failed" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Test failed
	at com.menumitratCommonAPITestScript.UdhariLeedgerCreateTestScript.testUdhariLedgerCreate(UdhariLeedgerCreateTestScript.java:285)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: org.json.JSONException: Expected a ':' after a key at 7 [character 8 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:503)
	at org.json.JSONObject.<init>(JSONObject.java:225)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.menumitratCommonAPITestScript.UdhariLeedgerCreateTestScript.testUdhariLedgerCreate(UdhariLeedgerCreateTestScript.java:209)
	... 22 more
]]>
    </error>
  </testcase> <!-- testUdhariLedgerCreate -->
</testsuite> <!-- com.menumitratCommonAPITestScript.UdhariLeedgerCreateTestScript -->
